lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'

    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: 'HS256'

    token_ttl: 10800

    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization